[package]
name = "kitty_render"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = {version = "0.30.1", features = ["ioctl"]}
# kitty_image = "0.1.0"
kitty_image = { git = "https://gitlab.com/fabiooo4/kitty-images.git" }
rand = "0.9.1"
termion = "4.0.5"
